---
- name: make a build dir
  file: state=directory name=/root/opentsdb-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/opentsdb-dockerized/Dockerfile

- name: put run
  template: src=run dest=/root/opentsdb-dockerized/run mode=0755


- name: build a Docker image for OpenTSDB
  docker_image:
    path:  /root/opentsdb-dockerized
    name:  gitinsky/opentsdb
    tag:   0.1.1
    state: present
  tags:
    - docker

- name: tag it as latest
  docker_image:
    path:  /root/opentsdb-dockerized
    name:  gitinsky/opentsdb
    state: build
  tags:
    - docker
