---
- name: make a build dir
  file: state=directory name=/root/opentsdb-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/opentsdb-dockerized/Dockerfile

- name: put run
  template: src=run dest=/root/opentsdb-dockerized/run mode=0755

- name: build a Docker image for OpenTSDB
  command: docker build -t gitinsky/opentsdb:0.1.1 --rm /root/opentsdb-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/opentsdb:latest --rm /root/opentsdb-dockerized
